## check development version of mboost
## see http://docs.travis-ci.com/user/languages/r/

language: r

r_github_packages:
  - boost-R/mboost
  - boost-R/gamboostLSS
  - jimhester/covr
  
r_packages:
  - TH.data
  - hdi
  - glmnet
  - lars
  - mboost
  - gamboostLSS
  
after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
