# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - ./travis-tool.sh install_deps
  ## install enhances
  - Rscript -e 'library("devtools"); library("methods"); options(repos=c(RForge="http://cran.rstudio.com")); install_deps(dependencies = "Enhances")'
  ## install newer versions of mboost and gamboostLSS
  # - Rscript -e 'library("devtools"); library(methods); options(repos=c(RForge="http://r-forge.r-project.org")); install_deps(dependencies = "Enhances")'
  - Rscript -e 'library("methods"); install.packages(c("mboost", "gamboostLSS"), repos= "http://r-forge.r-project.org")'
  
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
